version: '3.9'
services:
  nodeapp: 
    build: .
    container_name: nodeapp
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app
    restart: always
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"